const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'dhruvparmar2204@gmail.com',
        pass: 'jelw wmrs scvx hsrc'
    }
});

let mailOption = {
    from: '"Sender Name" <dhruvparmar2204@gmail.com>', // Sender address
    to: 'dhruvgamer2204@gmail.com', // List of recipients
    subject: 'Autogenerated Email', // Subject line
    text: 'Hello, this is an autogenerated email using nodemailer in Node.js!', // Plain text body
    html: '<b>Hello, this is an autogenerated email using nodemailer in Node.js!</b>' // HTML body
};

transporter.sendMail(mailOption, (error, info) => {
    if (error) {
        return console.log('There is an error:', error);
    }
    console.log('Message sent:', info.messageId);
    console.log('Preview URL:', nodemailer.getTestMessageUrl(info));
});
